PatrickF1/fzf.fish

functions/__fzf_search_shell_variables.fish

Resolves #10 
To repro the problem this PR is trying to address
1. set your SHELL variable to a different shell, e.g. `zsh`
2. execute the browse shell variable functionality
3. scroll over a variable
4. should see `zsh:1: command not found: __echo_or_print_message`, which is an indication that fzf is using the shell specified in SHELL to call the preview command

Make sure fzf uses fish to preview environment variables

---

functions/__fzf_search_history.fish

Making full use of the timestamp option for https://fishshell.com/docs/current/cmds/history.html
New log line example: `07/20 20:18:12 | help bind`.

Show command timestamps when searching command history

---

conf.d/fzf.fish
functions/uninstall.fish

The default keybindings were only being set up for default mode. Now, also set up the default keybindings for insert mode if the user is using fish_vi_key_bindings.
Resolves #13

Set keybindings when in vi mode

---

functions/__fzf_preview_file.fish
functions/__fzf_report_file_type.fish

File preview wasn't working on Linux and presumably Windows because the `file` command that ships with Mac, used to determine the file type, is outdated and has different options. See #19
Use `ls` to get the file type instead. Big thanks to @chshbh for the idea of using `ls`! He opened up a great PR in #20

fix file preview not working non non-Mac OSes

---

functions/__fzf_preview_file.fish

Use the builtin `test` repeatedly instead `command ls -o -d "$file_path" | string sub --length 1`. Running `test`, though having to do it multiple times, is much faster and less hacky. I have tested this by creating a named pipe with `mknod named-pipe-identifier p` and then spamming time `_fzf_preview_file named-pipe-identifier`. 200 microseconds vs. 3ms on my arch vm.

Use test builtin to get file type

---

README.md

1. Use prettier to format the README. Ensures consistent style, spacing, etc.
2. Reduce HTML use.
3. Use — (actual emdash character) instead of `&mdash;`.
Broken out from #30.

Format readme with prettier, use reference links

---

LICENSE.md

Convert license to markdown. As with README, CONTRIBUTING, CHANGELOG and the rest of the family, LICENSE is meant to be read by humans (granted no one ever actually reads the MIT license because we all know what it says, but still). Anything that is meant to be read by humans should be rendered by the browser into good looking HTML, not displayed as plain text.

Convert license to markdown

---

conf.d/fzf.fish

This commit fixes startup error messages of fzf.fish in case
$fish_key_bindings is not set.
If $fish_key_bindings is not set to a value, fzf.fish would generate the
following error messages on startup:
[: Missing argument at index 2
~/.config/fish/conf.d/fzf.fish (line 12):
if [ $fish_key_bindings = 'fish_vi_key_bindings' ]
^
from sourcing file ~/.config/fish/conf.d/fzf.fish
called on line 294 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
called during startup

put $fish_key_bindings inside quotes

---

functions/__fzf_search_git_status.fish

I mentioned this earlier and forgot. When running the `search_git_status` function, repaint should always be used (like in `search_git_log`) because something will always be printed.
Broken out from #30

Always repaint in search_git_status

---

conf.d/fzf.fish
functions/__fzf_search_current_dir.fish

A few incredibly minor edits:
1. Use `test` instead of `[ ... ]`, in accordance with documentation and the rest of the code. https://github.com/fish-shell/fish-shell/issues/1850 says that use of the square brackets for test is highly discouraged.
2. Use `2>/dev/null` instead of `2> /dev/null`. This is preferred by `fish_indent`. I can demonstrate this if you wish.
3. Use `string escape "$blah"` instead of `echo $blah | string escape`

Stylistic and more idiomatic code

---

README.md

Improve feature explanations by creating a new section and describe the features in a methodical and thorough way, each with their own sub-section.
Additionally, also improve explanations of configuration and troubleshooting.

Thoroughly document features and improve configuration section

---

functions/__fzf_preview_file.fish

This was some remnant code we failed to remove when switching from `ls` to `test`. I have chosen to not direct people to open an issue with this repository because there isn't really anything we could do--we are using all available file `test`s already.

Don't suggest reporting an issue for unknown file types in __fzf_preview_file

---

functions/__fzf_search_git_log.fish

This was causing a bash syntax error as it was failing to interpret the fish syntax used for subcommands on line 9 (`git show` etc).

Set the shell to fish in __fzf_search_git_log

---

functions/__fzf_search_history.fish

This is slightly opinionated, but there are two reasons for this change:
- More like ISO 8601 (`YYYY-MM-DD`)
- Reduce ambiguity with paths (no `/`)

Use %m-%d for history date format

---

README.md
functions/__fzf_search_current_dir.fish

This PR adds the following feature to File paths (<kbd>Ctrl</kbd> + <kbd>F</kbd>):
A dot and a slash (`./`) will be prepended automatically if:
- There is no input in the command line (the user triggers the function with a empty input)
- The user only made one selection
- The only selection is a directory
This makes it possible to quick enter the selected directory by pressing <kbd>Enter</kbd> again after making the selection. This is because [Fish treats it as implict `cd`](https://fishshell.com/docs/current/cmds/cd.html):
> Note that the shell will attempt to change directory without requiring cd if the name of a directory is provided (starting with ., / or ~, or ending with /).
<details>
<summary>
Screencast (Outdated)
</summary> …

Prepend ./ to single directory selections, allowing for quick cd

---

functions/__fzf_search_current_dir.fish
functions/__fzf_search_git_log.fish
functions/__fzf_search_git_status.fish
functions/__fzf_search_shell_variables.fish

Currect only "A previously run command" uses existing input as fzf's default query. I think this should apply to all functions.
For variable searching I did some extra work for leading `$`:
https://user-images.githubusercontent.com/44045911/103555474-4feac880-4eeb-11eb-918c-97878fa43180.mov

Always pre-populate fzf's search query with current token

---

functions/__fzf_extract_var_info.fish
functions/__fzf_preview_file.fish
functions/__fzf_search_current_dir.fish
functions/__fzf_search_git_log.fish
functions/__fzf_search_git_status.fish
functions/__fzf_search_history.fish
functions/__fzf_search_shell_variables.fish

Clean up function descriptions using the following criteria
- don't mention fzf, that's already obvious in the name of the function
- rather than writing about the function, write the description as if it is pseudo-code that emulates what the function does
- use sentence casing, following the Python style guide (https://devguide.python.org/documenting/)
- mention when previewing is built in
- prefer "output of git command" over "git noun of current repository", which is shorter and maybe less abstract
- "command line" is the proper spelling, not "commandline"
Also, for search shell variable:
- consolidated calls to `commandline --current-token`
- refactored logic for cleaning current token onto its own line so its documentation can be right above it and the call to fzf is shorter

Clean up and consolidate changes for v5

---

functions/__fzf_extract_var_info.fish
tests/extract_var_info_test.fish

The bug happens whenever the variable being previewed contains `|`. What happens is that the third regex used in `__fzf_extract_var_info` is greedy and will over-remove text up until the second to last `|`. For example:
```
$ set variable "a | b | c | d"
$ __fzf_extract_var_info variable (set --show | psub)
set in global scope, unexported, with 1 elements
[1]  d
```
With these changes, it now works properly:
```
$ set variable "a | b | c | d"
$ __fzf_extract_var_info variable (set --show | psub)
set in global scope, unexported, with 1 elements
[1] a | b | c | d
```
Additionally, I've added a Fishtape test to make debugging these tricky regexes more easily in the future, which I expect to need to do as fish shell on master has changed the output of `set --show`.

Fix bug in extracting variable values containing |

---

functions/__fzf_search_current_dir.fish
functions/__fzf_search_git_status.fish
functions/__fzf_search_history.fish
functions/__fzf_search_shell_variables.fish

User inputs, file names and commands can contain leading hypens (`--`), which may cause errors or the function not working.
Examples where fzf.fish would error:
- the cursor is over the token --something when the user executes find file
- the selected changed path from git status is -folder
- the selected command is --function
The solution is to delineate the end of options with --, which is a POSIX specification defined in https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02 (guideline 10), which is respected by Fish builtins. After --, the command will always interpret the arguments as positional arguments.

Prevent arguments from being interpreted as options

---

functions/__fzf_search_shell_variables.fish
tests/extract_var_info_test.fish
tests/search_shell_variables.fish

Adding Fishtape tests using Clownfish to mock commandline and fzf.

Add tests for search shell variables

---

functions/__fzf_search_current_dir.fish

Fix #88 
Fish's `test` and `fd` doesn't expand `~` automatically, so we need to expand it ourselves.

Expand tilde while searching files

---

.github/workflows/continuous_integration.yml
README.md
conf.d/fzf.fish
tests/extract_var_info/vars_containing_pipe.fish
tests/search_current_dir/expands_~_base_dir.fish
tests/search_shell_variables/$_in_curr_token.fish
tests/search_shell_variables/local_var.fish
tests/search_shell_variables/local_variables.fish
tests/search_shell_variables/no_args.fish

1. Put each test in its own file. From fishtape docs
> Each test file runs inside its own shell, so you can modify the global environment without cluttering your session or breaking other tests
2. Stopped making all the variables local, since I realized they won't pollute the session running the tests.
3. Replaced fish version badge with build status badge

Refactor: one folder per test suite, one file per test case

---

.github/workflows/continuous_integration.yml
functions/__fzf_preview_file.fish
functions/__fzf_search_current_dir.fish
tests/preview_file/follows_sym_links.fish
tests/preview_file/ls_hidden_without_double_dot.fish
tests/search_current_dir/expands_~_base_dir.fish
tests/search_current_dir/no_base_dir_if_no_slash.fish
tests/search_git_log/outputs_right_commit.fish
tests/search_git_status/outputs_right_paths.fish
tests/search_history/multi_line_cmd.fish

While I can't and don't plan on trying to test every possible code path, I can at least set up smoke tests. These smoke tests should catch many cases where a regression would completely break a feature, and thus prevent regressions from getting merged in. So while it won't obviate manual testing, it will cut down on manual testing for both me and anyone who wants to contribute to fzf.fish!

Automate smoke tests for every feature

---

functions/__fzf_preview_file.fish
functions/__fzf_search_current_dir.fish
tests/search_current_dir/no_dot_slash_if_unneeded.fish

If the file path already starts with . or /, which can happen if such a path was used as the base directory, then don't prepend ./.
Without such logic, the path becomes invalid. For example:
- if the current token is `/etc/` and you select `systemd`,  you end up with `'.//etc/systemd'`
- if the current token is `~/` and you select `Desktop`, you end up with `'./~/desktop'`
Additionally, since the output paths are quoted, we need to use the expanded token when outputting paths because ~ doesn't get expanded inside quotes.

Fix search file feature unnecessarily prepending ./

---

README.md
functions/__fzf_preview_file.fish
tests/preview_file/custom_dir_preview.fish

To acquiesce to the popularity and diversity of ls alternatives (e.g. https://github.com/ogham/exa, https://github.com/Peltoche/lsd, https://github.com/athityakumar/colorls, tree, all of which have many different options to configure them), I have finally decided to make the command used to preview directories configurable. Users can place their desired command in fzf_preview_dir_cmd and fzf.fish will use it.
Related to #117 and #101

Make preview directory command configurable

---

conf.d/fzf.fish

I believe you want this to be global.
If `fisher_path` is undefined and this file is in `$__fish_config_dir/conf.d`, it will already be global by default.
If `fisher_path` is defined, and `$fisher_path/conf.d` has to be sourced manually, it will default to local, which I believe is not intended.

Ensure variables set by conf.d/fzf.fish are global and update uninstaller

---

README.md
functions/__fzf_search_history.fish

Long commands get truncated in the fzf finder, while the spacing of multi-line commands are messed up. To remedy this,
show a preview of the entire command at the bottom.

Show command preview in history search

---

.github/workflows/continuous_integration.yml
conf.d/fzf.fish
functions/__fzf_extract_var_info.fish
functions/__fzf_preview_file.fish
functions/__fzf_search_git_status.fish
tests/search_current_dir/no_dot_slash_if_unneeded.fish
tests/search_git_log/outputs_right_commit.fish

I recently created two new github actions for Fish, [format-check](https://github.com/fish-actions/format-check), and [syntax-check](https://github.com/fish-actions/syntax-check). This PR adds them to the CI workflow. I also ran Fish 3.2's new `fish_indent` on the codebase so that `format-check` would be happy.

Check Fish syntax and format in CI

---

functions/__fzf_search_current_dir.fish

Just like #80, solves an issue introduced in https://github.com/PatrickF1/fzf.fish/pull/119/files#diff-fd01aaa375d8928720283f620b157dd451536fe8ef06d837110f2502b2f1660eR9.

[Search files] prevent token from being interpreted as an argument

---

functions/__fzf_search_history.fish

I happened to be visiting this repository, and I found a use for the trick I learned a little bit ago! Great idea @kidonng.
Sidenote, at this point I would argue for doing
```fish
set --local --export SHELL (command --search fish)
```
in every command by default somehow. We're already doing it in the majority.

[Search history] preview commands with fish_indent --ansi instead of bat

---

.github/workflows/continuous_integration.yml

Who knew https://docs.brew.sh/Homebrew-on-Linux existed? This is at least 5x faster and way less code.
Follow up from https://github.com/PatrickF1/fzf.fish/pull/137/files#r599225253

Use Homebrew to install fzf and fd on CI

---

README.md
functions/__fzf_search_current_dir.fish
functions/__fzf_search_git_log.fish
functions/__fzf_search_git_status.fish
functions/__fzf_search_history.fish
functions/__fzf_search_shell_variables.fish

The following variables can store the custom fzf options that will be passed to fzf by their respective feature:
fzf_dir_opts => search directory
fzf_git_status_opts => search git status
fzf_git_log_opts => search git log
fzf_history_opts => search history
fzf_shell_vars_opts => search shell variables
They are always appended last to fzf's argument list so that they can override any fzf options that are hardcoded in by fzf.fish. This might lead to some users shooting themselves in the foot but also unlocks numerous opportunities for the user to customize or augment the existing features. 
This was an oft requested feature that I parried for a long time but now I am very excited to finally add. With this, change, some of the cool ideas now made possible include 
- add key bindings within …

Allow passing custom fzf opts to individual commands

---

functions/__fzf_search_current_dir.fish

There was an zero-width space hiding before a comment throwing an error. (the character's invisible in a browser or terminal, but running `git diff dcf533 2c0fb5 | vim -` should make it visible)

Remove problematic character from __fzf_search_current_dir

---

functions/__fzf_search_git_log.fish

`%as` is added in [Git 2.25.0](https://git-scm.com/docs/git-log/2.25.0#Documentation/git-log.txt-emasem), and unfortunately I'm stuck on older Git versions on some machines, this PR makes fzf.fish compatible with them.
Or if you reject the change, you should also add minimal Git version requirement to README.

[Search git log] improve compatibility with older git versions

---

README.md
functions/__fzf_preview_file.fish
tests/preview_file/custom_file_preview.fish

Based on the current implementation for directories. Seems straightforward
enough to me, but please let me know if I overlooked something.

[Search directory] allow customizing the file preview command

---

functions/__fzf_preview_file.fish

There is still, yet another bug, afflicting the search directory feature. To reproduce, `set -x fzf_preview_dir_cmd ls` and search with a base directory with spaces in its name:
As it turned out, escaping quotes isn't a good idea either. The correct way to use `eval` is to quote the code entirely. Single quotes for parameter is used for programs instead.
This is a followup from #137 and #152

[Search directory] fix preview when base dir contains spaces (patch 3)

---

functions/__fzf_preview_file.fish

Due to #152, this is broken while all other `$file_path` references have been correctly quoted.

[Search directory] fix previewing symlinks containing spaces

---

functions/__fzf_search_current_dir.fish

This was presented in the [initial PR](https://github.com/PatrickF1/fzf.fish/pull/75) when the feature is added, but was (possibly mistakenly) broken by #137.

[Search directory] fix specifying base directories using quotes

---

README.md
functions/__fzf_search_shell_variables.fish
tests/search_shell_variables/$_in_curr_token.fish

This feature started with the discussion in https://github.com/PatrickF1/fzf.fish/pull/73#discussion_r552143666.
After such a long time I'm convinced that keeping `--multi` in `FZF_DEFAULT_OPTS` is not a good idea, but we can make more functions allow multiple selections by default.
IMO, out of 5 current fzf.fish functions, only `__fzf_search_history` does not need `--multi`. `__fzf_search_current_dir` and `__fzf_search_git_status` already has `--multi` by default, which is natural since they deal with files.
`__fzf_search_shell_variables` joins the party in this PR, the most prominent usage I can think of now is `set -e` multiple variables.
As for `__fzf_search_git_log`, that will be in a separate PR since we may need to discuss how to handle multiple selections there (it's not as simple …

[Search variables] enable selecting multiple variables

---

functions/_fzf_configure_bindings_help.fish

I got confused by this; I am assuming `fzf_configure_bindings --help` should show the default key bindings, which were different from what was documented.

Fix default key sequence doc in fzf_configure_bindings

---

.github/workflows/continuous_integration.yml
conf.d/fzf.fish

All of fzf.fish's features are only relevant and helpful in interactive mode. However, its config gets sourced even in non-interactive mode. So, let's skip configuration in non-interactive mode to make non-interactive fish shells a bit faster. This greatly benefits other plugins as well; for example [tide](https://github.com/IlanCosman/tide) makes use of non-interactive fish shells extensively.

Skip config if not in interactive mode

---

conf.d/fzf.fish
functions/fzf_configure_bindings.fish

This fixes #183, which is a resulting bug from #180.
#180 makes `$_fzf_search_vars_command` unavailable for non-interactive sessions. However, `fzf_configure_bindings` depends on that variable being available. If the user puts `fzf_configure_bindings` in their `config.fish`, `fzf_configure_bindings` gets executed in non-interactive sessions e.g. fzf preview windows or by tide, and the following line in the function...
https://github.com/PatrickF1/fzf.fish/blob/17d54b576919ee77644779db2dcae56d372a8830/functions/fzf_configure_bindings.fish#L33
...essentially becomes: 
```fish
test -n $key_sequences[5] && bind --mode $mode $key_sequences[5]
```
which results in error message like `bind --preset \cv fish_clipboard_paste` or `bind: No binding found for sequence '\cv'`.
Don't execute the …

Fix bind error messages appearing in non-interactive windows

---

README.md
functions/_fzf_search_directory.fish
tests/search_current_dir/append_trailing_slash.fish
tests/search_current_dir/appending_trailing_slash.fish
tests/search_current_dir/no_dot_slash_if_unneeded.fish

I decided appending / is a better, cleaner solution for quick cd than appending ./
- since prepending ./ is causing issues when the path starts with . or /, why not just append /? fd never appends / to its output so this is safe to do (see https://github.com/sharkdp/fd/issues/436)
- of course, we can't just append / to everything; we need to test if the path is actually a directory, but since we only do this when there's one path selected, it's not performance hindering
- a / at the end of only directories is cleaner, natural, and has a more comprehensible than prepending ./ to anything even when it's not needed
- the code and documentation become much more straightforward
- this will remove support for executables, which cuts back on product debt
- fixes #171 (is compatible with hidden …

[Search directory] Append / instead of prepending ./ for quick cd

---

README.md
conf.d/fzf.fish
functions/_fzf_configure_bindings_help.fish
functions/_fzf_search_directory.fish
functions/_fzf_search_git_log.fish
functions/_fzf_search_git_status.fish
functions/_fzf_search_history.fish
functions/_fzf_search_variables.fish
functions/_fzf_wrapper.fish
tests/wrapper/doesnt_clobber_env.fish

Create a wrapper around internal execution of fzf, and in it set `SHELL` and `FZF_DEFAULT_OPTS`. This has three huge advantages:
1. Before `FZF_DEFAULT_OPTS` was set in config.fish. By moving that code into an internal wrapper, we no longer meaningfully dirty the shell environment. This means fewer side-effects as a result of installing this plugin and so feels a lot purer.
2. This eliminates the problem of properly uninstalling the default `FZF_DEFAULT_OPTS` in the uninstall function.
2. We have finally consolidated of the code that forces `SHELL` to be fish.

Set SHELL and FZF_DEFAULT_OPTS in wrapper around fzf

---

functions/_fzf_extract_var_info.fish

This fixes displaying the value of variables in the variable preview.
This change confuses me for the following observations:
escaping the $ inside the regex should never work as intended (as far as I understand), but using fish 3.3.1 the existing code somehow works in the first fish instance I start after deleting the fish_variables file.
The changed code always works for me.

[Search variables] Remove excessive escape for replacement

---

functions/_fzf_search_directory.fish

[fd 8.3.0](https://github.com/sharkdp/fd/releases/tag/v8.3.0) introduced a `--strip-cwd-prefix` flag to revert a new behavior: `./` prefix is shown when output is not a tty (terminal).
This is what you get in `_fzf_search_directory` without this patch:
And with this patch:

Hide ./ prefix when fd version >= 8.3.0

---

functions/_fzf_search_processes.fish

`ps` outputs in a tabular format, and since the `_fzf_search_processes` function runs `ps` for a single process to generate the preview, the content of the preview is much more "horizontal" (similar to the `_fzf_search_history` function) since it's a single row of information.
This PR specifies that the `preview-window` for `_fzf_search_processes` should be on the bottom, 4 pixels tall, and wrapped. Since the header will always take up the first line, this gives the `COMMAND` 3 lines to wrap (same amount of lines that `_fzf_search_history` gives commands to wrap).

Put `preview-window` on bottom in `_fzf_search_processes`

---

functions/_fzf_search_git_status.fish
tests/search_git_status/outputs_right_paths.fish
tests/wrapper/doesnt_clobber_env.fish

This fixes a bug where file paths outputted by search git status include an extra layer of single quotes if the path includes a space. Turns out this is because we string escape all our paths before writing them to the command line but git status already string escapes paths with spaces.
Fixes #220

[Search git status] fix extra quotes from spaced file paths

---

README.md
functions/_fzf_search_processes.fish

First, thanks for your effort in getting the process search feature in! I saw the mention but unfortunately don't have the time to chime in.
I was not satisfied as you did, and made some local changes to fzf.fish. It was until #227 got merged that I realized I never submitted those patches (yes, I have been putting the preview window on the bottom for the longest time).
So here is the change that I really want to upstream: mark exited process as red.
Since [the preview is provided by a second `ps`](https://github.com/PatrickF1/fzf.fish/blob/a033d17b6d0288400b34c69911822e879b7d98bd/functions/_fzf_search_processes.fish#L12), the selected process may have already exited and all we get is a confusing header.
_Where is that process I want to look at?_
Even if it exited, the full process name …

[Search processes] account for exited processes in preview

---

README.md

Earlier today I wanted to stop excluding files from the `.gitignore`. However I got briefly stuck as I tried and failed to find the culprit in your codebase, not realizing this was a default setting of `fd`. I thought a note clarifying this and giving a solution might be appreciated by others with the same troubles.
Thanks for the great plugin.

add note clarifying .gitignore behavior

---

README.md
functions/_fzf_preview_changed_file.fish
functions/_fzf_preview_file.fish
functions/_fzf_preview_status.fish
functions/_fzf_search_git_status.fish

Add a preview for the changed file

[Search git status] preview changed files

---

functions/_fzf_search_history.fish

Calling `history merge` in private mode (`fish --private`) **clears** the session history. So if you execute the search history function while in private mode, there is no history to search.

[Search history] don't merge history when in private mode

---

functions/_fzf_search_history.fish

A small flaw with https://github.com/PatrickF1/fzf.fish/pull/252 was that it didn't preserve the boundaries between commands and so at the end, it had to check each line of output for the timestamps and remove them. Not only was that it inefficient and a little hard to understand, it could potentially result in a bug if a command ever included a line that began with "$datetimestring | ". 
A better solution is to keep each command selected as an individual argument throughout the entire pipeline by delineating them with nulls, which is thankfully supported by fzf and fish string utils. Additionally, I realized the logic of stripping out the timestamps could be elegantly integrated into the [pipeline](https://en.wikipedia.org/wiki/Pipeline_(Unix)).

[Search history] simplify logic into pipeline

---

README.md
functions/_fzf_preview_changed_file.fish
tests/preview_changed_file/deleted_in_working.fish
tests/preview_changed_file/merge_conflict.fish
tests/preview_changed_file/modified_in_both.fish
tests/preview_changed_file/path_with_spaces.fish

Also, update some comments and docs for Search git status.

[Search git status] support previewing merge conflict

---

README.md

Cons of gifs
- can't pause or rewind to catch the details you missed
- continually plays so can be distracting
- very tedious to record and update every time fzf.fish's UI changes
- they all look the same at the beginning with an empty command line, so hard to distinguish as you scroll through
- requires users to patiently wait for it to completely loop to see the preview functionality, which is what is most eye catching
Solution
- GitHub recently released video upload! https://github.blog/2021-05-13-video-uploads-available-github
- one demo video edited to show key bindings at the top showcasing the features that can the user can pause, rewind, seek 
- screenshots below each feature that statically present each command's most eye catching preview functionality

Replace gifs in readme with one demo video and screenshots

---

functions/_fzf_search_git_log.fish

Fixed the raw GPG output that leaked in the commit list for repos that have the `showSignature = true` git configuration. The values of the check are specified in the [`%G?` format specifier](https://git-scm.com/docs/git-log#Documentation/git-log.txt-emGem) for `git log`
Resolves #286

Added GPG output check

---

functions/_fzf_report_diff_type.fish
tests/preview_changed_file/deleted_in_working.fish
tests/preview_changed_file/merge_conflict.fish
tests/preview_changed_file/modified_in_both.fish

This makes the little header box for Git staged/unstaged/merged/etc. look a bit nicer.
Old:
```
+--------+
| Staged |
+--------+
```
New:
```
╭────────╮
│ Staged │
╰────────╯
```
It does not look perfect on GitHub web, but works in a terminal with a proper font:
We could make this optional (add some `$_fzf_fish_use_unicode_box` variable), but `fzf` itself is
also using those box drawing characters by default, so I guess pretty much everyone using `fzf.fish`
should be fine with it.

[Search Git Status] use box drawing chars for staged/unstaged header

---

README.md
functions/_fzf_search_history.fish

Enable configuring the format of command execution times in Search History through the new `fzf_history_time_format` variable. This is highly valuable for non-US users who may be accustomed to reading dates as day-month (rather than month-day as the default is), or for people who want to search through previous years of command history.

[Search history] Make date time format configurable

---

functions/_fzf_search_git_log.fish
functions/_fzf_search_history.fish

This improves ranking by using age not only as tiebreaker, but giving it more weight. I for example have some commands which I use almost daily but which always appear third or even lower in the list, due to some other commands (which I didn't use for months) matching *a little bit* better.
From the man page:
```
--scheme=SCHEME
Choose scoring scheme tailored for different types of input.
default  Generic scoring scheme designed to work well with any type of input
path     Scoring scheme for paths (additional bonus point only after path separator)
history  Scoring scheme for command history (no additional bonus points).
Sets --tiebreak=index as well.
```

[Search History][Search Git Log] use history scoring scheme

---

README.md

[exa](https://github.com/ogham/exa/issues/1243) is now unmaintained. `eza` is a fork that is essentially a drop in replacement for `exa`. This PR encourages its use over the former. 😄

replace exa with eza in example now that exa is unmaintained

---

functions/_fzf_search_directory.fish
functions/_fzf_search_git_log.fish
functions/_fzf_search_git_status.fish
functions/_fzf_search_history.fish
functions/_fzf_search_processes.fish
functions/_fzf_search_variables.fish

There is no need to specify "Search" in input prompts since that's all fzf does.
Reducing prompt length helps with reading, especially in limited spaces (e.g. terminal splits).

Remove unnecessary "Search" from prompts

---

README.md
functions/_fzf_wrapper.fish

Don't set default fzf options if FZF_DEFAULT_OPTS_FILE is set. FZF_DEFAULT_OPTS_FILE was added to fzf in version [0.47.0](https://github.com/junegunn/fzf/releases/tag/0.47.0)

Add support for FZF_DEFAULT_OPTS_FILE
